version: '2'
services:
  osticket-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: osticket
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: osticket
    volume_driver: ${VOL_DRIVER}
    stdin_open: true
    volumes:
    - ${VOL_NAME}:/var/lib/mysql
    tty: true
  osticket:
    image: campbellsoftwaresolutions/osticket
    environment: 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      INSTALL_NAME: ${INSTALL_NAME}
    ports: 
    - "8080:80"
    stdin_open: true
    tty: true
