version: '2'
services:
    mariadb:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
        volume_driver: ${VOL_DRIVER}
        volumes:
        - ${DB_VOLUME}:/var/lib/mysql
    wordpress:
        image: wordpress
        volumes:
        - ${WP_VOLUME}:/var/www/html
        volume_driver: ${VOL_DRIVER}
        links:
        - mariadb:mysql
        - vsftpd:internal-ftp
        ports:
        - ${WP_PORT}:80/tcp
    vsftpd:
        image: fauria/ftp
        environment:
          FTP_USER: ${FTP_USER}
          FTP_PASS: ${FTP_PASS}
        volumes:
        - ${WP_VOLUME}:/home/vsftpd
        volume_driver: ${VOL_DRIVER}
